name: taxi_booking
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

analyzer:
  enable-experiment:
    - non-nullable

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.1.5
  google_maps_flutter: ^2.0.0
  location: any
  sliding_up_panel: ^2.0.0+1
  geocoding: ^2.0.1
  sqflite: ^2.0.0+4
  path_provider: ^2.0.0
  extended_masked_text: ^2.3.1
  fluttertoast: ^8.0.9
  dio: ^4.0.0
  shared_preferences: ^2.0.7
  carousel_slider: ^4.0.0
  provider: ^6.0.4
  flutter_spinkit: ^5.1.0
  flutter_local_notifications: ^12.0.2
  percent_indicator: ^4.2.2
  google_maps_webservice: ^0.0.20-nullsafety.2
  get_it: ^7.2.0
  geolocator: ^9.0.2
  uuid: ^3.0.5
  flutter_polyline_points: ^1.0.0
  google_directions_api: ^0.9.0
  maps_toolkit: ^2.0.0
  flutter_google_places: ^0.3.0
  connectivity: ^3.0.6
  pin_code_text_field: ^1.8.0
  flutter_map: any
  flutter_geofire: ^2.0.0
  animated_text_kit: ^4.2.1
  font_awesome_flutter: ^10.2.1
  google_place: ^0.4.3
  flutter_map_tappable_polyline: ^3.1.0
  google_maps_widget: ^1.0.4
  flutter_animarker: ^3.2.0
  webview_flutter: ^3.0.4
  flutter_progress_hud: ^2.0.0
  firebase_auth: ^3.11.2
  firebase_core: ^1.11.0
  pin_entry_text_field: ^0.1.4
  url_launcher: ^6.1.6
  easy_localization: ^3.0.0
  image_picker: ^0.8.4+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  dart_code_metrics: ^4.1.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/countrycodes.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/bolt-regular.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/bolt-semibold.ttf

    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

